[package]
name = "bitweiser"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
colored = "2.1.0"
miette = { version = "7.4.0", features = ["fancy"] }
paste = "1.0.15"
static_assertions = "1.1.0"
thiserror = "2.0.3"
